---

- name: Install PHP and associated packages
  dnf: 
    name: 'http://rpms.remirepo.net/fedora/remi-release-27.rpm'
    state: present

- name: Install PHP CLI
  dnf: 
    name: php-cli
    state: present

- name: Install PHP Modules
  dnf: 
    name: php-mysqli
    state: present
  notify:
    - Restart Apache
